### PR TITLE
Update script for recent Forge Architecture changes

### PR DESCRIPTION
**Pull request by wcole3**
This PR makes changes needed to get the extension running in Forge after the recent architectural changes in that framework including the update to Gradio 4.  This branch does not include changes to allow the extension to work with Flux based models.

I've tried to maintain compatibility with auto1111, but I have not tested these changes in that repo.  

I'm happy to close this if you're not interested or have better ideas for updates, but I figured I'd post the branch in case people are interested in using this.

Possibly related to #27 #28

### CODE REVIEW

**Comment by SecretBeast669** [comment]
Thank you so much! I can finally use this extension on new Forge.

**Comment by boredafk** [comment]
Can you fix this one too? https://github.com/gustproof/sd-webui-forge-style-components

**Comment by wcole3** [comment]
Is there something in that extension thaat isn;t available in the Forge builtin ipadapter extension?

**Comment by boredafk** [comment]
It's Anime. and It can apply random styles, Not just ones from images

**Comment by wcole3** [comment]
[See PR](https://github.com/gustproof/sd-webui-forge-style-components/pull/4)  please let me know if you encounter errors

**Comment by boredafk** [comment]
*** Error calling: /home/studio-lab-user/forge/extensions/sd-webui-cd-tuner/scripts/cdtuner.py/ui
    Traceback (most recent call last):
      File "/home/studio-lab-user/forge/modules/scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "/home/studio-lab-user/forge/extensions/sd-webui-cd-tuner/scripts/cdtuner.py", line 88, in ui
        refresh_d1 = ToolButton(value=resetsymbol)
      File "/home/studio-lab-user/forge/extensions/sd-webui-cd-tuner/scripts/cdtuner.py", line 38, in __init__
        super().__init__(variant="tool",
      File "/home/studio-lab-user/forge/modules/gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/components/button.py", line 61, in __init__
        super().__init__(
      File "/home/studio-lab-user/forge/modules/gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/components/base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "/tmp/venv/lib/python3.10/site-packages/gradio/components/base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'cdtuner.py'

---
*** Error calling: /home/studio-lab-user/forge/extensions/sd-webui-cd-tuner/scripts/cdtuner.py/ui
    Traceback (most recent call last):
      File "/home/studio-lab-user/forge/modules/scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "/home/studio-lab-user/forge/extensions/sd-webui-cd-tuner/scripts/cdtuner.py", line 88, in ui
        refresh_d1 = ToolButton(value=resetsymbol)
      File "/home/studio-lab-user/forge/extensions/sd-webui-cd-tuner/scripts/cdtuner.py", line 38, in __init__
        super().__init__(variant="tool",
      File "/home/studio-lab-user/forge/modules/gradio_extensions.py", line 147, in __repaired_init__
        original(self, *args, **fixed_kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/components/button.py", line 61, in __init__
        super().__init__(
      File "/home/studio-lab-user/forge/modules/gradio_extensions.py", line 36, in IOComponent_init
        res = original_IOComponent_init(self, *args, **kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/component_meta.py", line 163, in wrapper
        return fn(self, **kwargs)
      File "/tmp/venv/lib/python3.10/site-packages/gradio/components/base.py", line 229, in __init__
        self.component_class_id = self.__class__.get_component_class_id()
      File "/tmp/venv/lib/python3.10/site-packages/gradio/components/base.py", line 118, in get_component_class_id
        module_path = sys.modules[module_name].__file__
    KeyError: 'cdtuner.py' cd tuner

**Comment by wcole3** [comment]
You have not checked out the correct branch

**Comment by hako-mikan** [comment]
Thanks!!

**Pull request merged**
